version: '3'

services:
  mysqldb:
    container_name: dbcontainer
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'indexcardsdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    networks:
      - springmysql-net
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - my-db:/var/lib/mysql
  backend:
    container_name: backendcontainer
    build: ./indexcards
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/indexcardsdb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_PASSWORD: '1234'
    volumes:
      - './indexcards:/usr/src/app'
    ports:
      - '8081:8080'
    networks:
      - springmysql-net
      - backend
      - nginx_backend
    restart: always
    depends_on:
      - mysqldb
  frontend:
    container_name: frontendcontainer
    build: ./indexcards-ui
    volumes:
      - './indexcards-ui:/usr/src/app'
    restart: always
    depends_on:
      - backend
    networks:
      - backend
      - nginx_backend
    ports:
      - '4200:80'

networks:
  springmysql-net:
  backend:
  nginx_backend:
    external: true


volumes:
  my-db: