-- Schema as previously generated by Hibernate (ddl-auto) for MySQL.
-- Existing databases are baselined at version 1 (spring.flyway.baseline-on-migrate), so this only runs on empty ones.

create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );

create table user (user_id bigint not null, firstname varchar(100) not null, password varchar(100) not null, surname varchar(100) not null, username varchar(100) not null, primary key (user_id)) engine=InnoDB;
create table project (project_id bigint not null, exam_date date, name varchar(100) not null, user_id bigint, primary key (project_id)) engine=InnoDB;
create table indexcards (indexcard_id bigint not null, answer longblob not null, assessment integer not null, due_date datetime(6), ease_factor double precision, interval_days integer, question longblob not null, repetitions integer, project_id bigint, primary key (indexcard_id)) engine=InnoDB;
create table indexcardassessment (indexcard_assessment_id bigint not null, assessment integer not null, date datetime(6) not null, primary key (indexcard_assessment_id)) engine=InnoDB;
create table indexcards_assessment_history (index_card_indexcard_id bigint not null, assessment_history_indexcard_assessment_id bigint not null, primary key (index_card_indexcard_id, assessment_history_indexcard_assessment_id)) engine=InnoDB;

alter table indexcards_assessment_history add constraint UK_qxuitw3widusvpnwlm9868f9r unique (assessment_history_indexcard_assessment_id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (user_id);
alter table indexcards add constraint FKm96550a5xu1jwr1mb4kqnfxwc foreign key (project_id) references project (project_id);
alter table indexcards_assessment_history add constraint FKhwc8vc2ilfygoau29dck9bo1u foreign key (assessment_history_indexcard_assessment_id) references indexcardassessment (indexcard_assessment_id);
alter table indexcards_assessment_history add constraint FKaiklo5l7nu0qdkqp4sqguvu9u foreign key (index_card_indexcard_id) references indexcards (indexcard_id);
