# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: indexcard pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B package --file indexcards/pom.xml
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd indexcards-ui && npm ci

      - name: Code Linting
        run: cd indexcards-ui && npm run lint
  deploy:
    name: Deployment
    runs-on: self-hosted
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      - name: Start docker-compose
        run: |
          export ${{ secrets.DB_PASSWORD }}
          docker-compose down
          docker-compose up --build -d
        if: github.event_name != 'pull_request'
  documentation:
    name: Deploy documentation
    runs-on: self-hosted
    needs:
      - deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      - name: Start docker-compose
        run: |
          cd indexcards-docu
          docker-compose down
          docker-compose up --build -d
        if: github.event_name != 'pull_request'